- name: Install MySQL and configure database
  hosts: 10.0.2.15
  become: yes
  vars_files:
  - vault.yml
  tasks:
  - name: update and install mysql
    apt:
      name:
      - mysql-server
      - python3-mysqldb
      state: present
      update_cache: yes

  - name: Ensure MySQL running

    service:
      name: mysql
      state: started
      enabled: yes


  - name: Create MySQL database
    mysql_db:
      name: ivolve_ojt
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

  - name: Create MySQL user 
    mysql_user:
      name: ahmed
      password: "{{ db_user_password }}"
      priv: '.:ALL'
      login_user: root
      login_password: "{{ mysql_root_password }}"
