---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nti-resource-quota
  namespace: nti
spec:
  hard:
    pods: "10"
    requests.cpu: "0.5"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi

